name: Clean SISI Cache

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  clean-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Execute clean command on Render
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-d8lg3n8g4nts73932rm0/commands" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"command": "rm -rf /app/wwwroot/bookmarks/* /app/cache/*"}'
